name: Build CI and Release

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-pio:
    name: Build PlatformIO
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.13'
      - name: Install python
        run: sudo apt-get install python3 python3-pip
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run --environment x4_relay

      - name: Move and rename firmware
        run: mv .pio/build/x4_relay/firmware.bin ./firmware_os_x4_relay.bin

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: ./firmware_os_x4_relay.bin
